# Generated by Django 5.1.6 on 2025-03-05 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], max_length=10)),
                ('num_copies', models.IntegerField(default=1)),
                ('print_type', models.CharField(choices=[('black_white', 'Black & White'), ('color', 'Color')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
