# Generated by Django 5.1.7 on 2025-03-11 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_store_printorder_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='file_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='file_path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='num_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='num_pages',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.store'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
