# Generated by Django 5.1.7 on 2025-03-20 19:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_store_printorder_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printorder',
            options={'verbose_name': 'Print Order', 'verbose_name_plural': 'Print Orders'},
        ),
        migrations.AlterField(
            model_name='printorder',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
