# Generated by Django 5.1.6 on 2025-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_printorder_options_alter_printorder_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='aes_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printorder',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printorder',
            name='iv',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
