# Generated by Django 5.1.7 on 2025-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_store_latitude_store_longitude_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Store Location'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Store Name'),
        ),
    ]
